const mongoose = require('mongoose');
const contactModel = mongoose.Schema({
    companyId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'company',
    },
    // Basic info

    CoantactType: String,
    AddProfile: String,
    Prefix: String,
    FirstName: String,
    MiddleName: String,
    LastName: String,
    Suffix: String,
    PreferredName: String,
    Gender: String,
    DateofBirth: String,
    Email: String,
    EmailType: String,
    OnHold: String,
    BulkMailings: String,
    SelectYourIdType: String,
    EnterIdNo: String,
    CurrentEmployer: String,
    JobTitle: String,
    AdditionalInfo: String,
    Phone: Array,
    ContactLocation: String,
    InstantMessenger: Array,
    IMLocation: String,
    IMType: String,
    SocialMediaName: String,
    Username: String,
    Website: String,
    ReferralContact: String,
    ReferralID: String,
    Testimonials: String,
    AddProfessionalCertificates: String,
    EmployeeStatus: String,
    ConvenientTimeforreachingouttoyou: String,
    LevelEducation: String,
    FavoriteColour: String,
    MostPreferredHolidayDestination: String,
    FavoritesBrands: String,
    FavoriteleisuretimeActivities: String,
    MostUsedApps: String,
    FavoriteSites: String,
    PreferredsocialMediaPlatform: String,
    NativePlace: String,
    Languagesknown: String,
    FavoriteNiche: String,
    PreferredShoppingMethod: String,
    Shoppingwebsitespreferredotherthanus: String,
    Religion: String,
    FoodTypepreferred: String,
    WorkoutTypepreferred: String,
    BloodGroup: String,
    CharitiesRelatedto: String,
    Closetoheartsocialservices: String,
    MostImportantIssue: String,
    MartialStatus: String,
    MarriageAnniversaryDate: String,
    FamilyStrength: String,
    Relation: String,
    Name: String,
    Age: String,
    WorkingorDependent: String,
    PhoneNumber: String,
    SearchCurrentAddress: String,
    AddressType: String,
    Primarylocationforthiscontact: String,
    Billinglocationforthiscontact: String,
    Useanothercontactsaddress: String,
    UnitNumber: String,
    StreetNumber: String,
    StreetName: String,
    StreetType: String,
    Country: String,
    SelectTimezone: String,
    State: String,
    City: String,
    PostalCode: String,
    CommunicationStyle: String,
    SalutationType: String,
    Privacy: String,
    PreferredCommunicationMethod: String,
    PreferredLanguage: String,
    EmailFormat: String,
    NOBULKEMAILS: String,
    Tag: String,
    Group: String,
    ReferenceFrom: String,
    date: {
        type: Date,
        default: Date.now()
    }
});

//.exports.Contact = Contact;
module.exports = mongoose.model("contact", contactModel);